# Generated by Django 2.2 on 2019-07-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190728_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
