# Generated by Django 2.1.2 on 2018-10-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181027_1841'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('title',)},
        ),
    ]
