# Generated by Django 2.1.2 on 2018-10-27 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181027_1843'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name',)},
        ),
    ]
