# Generated by Django 2.2 on 2019-09-08 17:42

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190907_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, help_text='Enter Your Address', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default=datetime.datetime(2019, 9, 8, 17, 42, 31, 52437, tzinfo=utc), help_text='Enter Your City', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(default=111234445, help_text='Enter Your Country', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.CharField(default=1234455554455454, help_text='Enter Your Zip Code', max_length=100),
            preserve_default=False,
        ),
    ]
