# Generated by Django 2.1.2 on 2018-11-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='count_words',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
