# Generated by Django 2.2 on 2019-04-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190413_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner_image',
            field=models.ImageField(default='slider-1.jpg', upload_to='banner'),
        ),
    ]
