# Generated by Django 2.2 on 2019-04-15 14:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_profile_banner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default=django.utils.timezone.now, help_text='Short Bio (eg. I love cats and games)', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job_title',
            field=models.CharField(default=122344, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='twitter_url',
            field=models.URLField(default='#'),
        ),
    ]
